#pragma once

#define LCD_WIDTH 320
#define LCD_HEIGHT 240

//---------------------------------------------

#ifndef PRINT_THROTTLE
#define PRINT_THROTTLE 0
#endif
#ifndef PRINT_COMMS_FSM_STATE
#define PRINT_COMMS_FSM_STATE 0
#endif
#ifndef PRINT_COMMS_FSM_TRIGGER
#define PRINT_COMMS_FSM_TRIGGER 0
#endif
#ifndef PRINT_TX_TO_CONTROLLER
#define PRINT_TX_TO_CONTROLLER 0
#endif
#ifndef PRINT_RX_FROM_CONTROLLER
#define PRINT_RX_FROM_CONTROLLER 0
#endif
#ifndef PRINT_FOOTLIGHT_FSM_STATE
#define PRINT_FOOTLIGHT_FSM_STATE 0
#endif
#ifndef PRINT_FOOTLIGHT_FSM_TRIGGER
#define PRINT_FOOTLIGHT_FSM_TRIGGER 0
#endif
#ifndef PRINT_DISP_FSM_STATE
#define PRINT_DISP_FSM_STATE 0
#endif
#ifndef PRINT_DISP_FSM_TRIGGER
#define PRINT_DISP_FSM_TRIGGER 0
#endif
#ifndef USING_M5STACK
#define USING_M5STACK 0
#endif